#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards on `/app` folder
yarn fe:format ||
(
    echo '🤢🤮🤢🤮 Prettier Check Failed. Run yarn format, add changes and try to commit again.';
    false;
)

# Check ESLint Standards on `/app` folder
yarn fe:lint ||
(
    echo '😤🏀👋😤 ESLint Check Failed. Make the required changes listed above and try to commit again.'
    false; 
)

# Check Prettier standards on `/backend` folder
yarn be:format ||
(
    echo '😤🏀👋😤 ESLint Check Failed. Make the required changes listed above and try to commit again.'
    false; 
)

# Check ESLint Standards on `/backend` folder
yarn be:lint ||
(
    echo '🤢🤮🤢🤮 Prettier Check Failed. Run yarn format, add changes and try to commit again.';
    false; 
)

# Run BE tests
#yarn be:e2e ||
#(
#    echo "😤🏀👋😤 Test Failed, buggy code. I ain't going to commit this, the hell! - Try again."
#    false; 
#)
